name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2

      # Install R package dependencies, with error handling
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("remotes", repos = "https://cran.rstudio.com")'
          Rscript -e 'remotes::install_cran(c("seasonalityPlot", "rcmdcheck"), repos = "https://cran.rstudio.com")' || exit 1

      - uses: r-lib/actions/check-r-package@v2
